# Generated by Django 5.0.6 on 2024-07-06 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazarentry',
            old_name='money_left',
            new_name='money_given',
        ),
    ]
