# Generated by Django 5.0.6 on 2024-07-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazarentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.person'),
        ),
        migrations.AlterField(
            model_name='mealentry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.person'),
        ),
    ]
