# Generated by Django 5.0.6 on 2024-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_person_money_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazarentry',
            name='money_left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bazarentry',
            name='serial_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
