# Generated by Django 5.0.6 on 2024-07-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_bazarentry_money_left_alter_bazarentry_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazarentry',
            name='money_left',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
