# Generated by Django 5.0.7 on 2024-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_bazarentry_money_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazarentry',
            name='money_take_from_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
